import { TextEdit, LineEdit, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { CustomTab } from "shared.slint";

export component RequestPanel inherits VerticalBox {
    in-out property <string> active-tab: "Params";
    in-out property <string> body-text: "";
    in-out property <string> header1-key: "";
    in-out property <string> header1-val: "";
    in-out property <string> header2-key: "";
    in-out property <string> header2-val: "";
    
    spacing: 0px;
    padding: 10px;

    HorizontalBox {
        alignment: start;
        spacing: 10px;
        CustomTab { text: "Params"; active: active-tab == "Params"; clicked => { active-tab = "Params" } }
        CustomTab { text: "Auth"; active: active-tab == "Auth"; clicked => { active-tab = "Auth" } }
        CustomTab { text: "Headers"; active: active-tab == "Headers"; clicked => { active-tab = "Headers" } }
        CustomTab { text: "Body"; active: active-tab == "Body"; clicked => { active-tab = "Body" } }
    }
    
    Rectangle {
        height: 1px;
        background: #888888;
        opacity: 0.3;
    }
    Rectangle { height: 10px; }

    if active-tab == "Params" : VerticalBox {
        HorizontalBox {
            LineEdit { placeholder-text: "Key"; }
            LineEdit { placeholder-text: "Value"; }
            LineEdit { placeholder-text: "Description"; }
        }
    }
    
    VerticalBox {
        visible: active-tab == "Headers";
        spacing: 5px;
        HorizontalBox {
            LineEdit { placeholder-text: "Key (ex: Content-Type)"; text <=> root.header1-key; }
            LineEdit { placeholder-text: "Value (ex: application/json)"; text <=> root.header1-val; }
        }
        HorizontalBox {
            LineEdit { placeholder-text: "Key (ex: Authorization)"; text <=> root.header2-key; }
            LineEdit { placeholder-text: "Value (ex: Bearer token)"; text <=> root.header2-val; }
        }
    }
    
    VerticalBox {
        visible: active-tab == "Body";
        TextEdit {
            text <=> root.body-text;
        }
    }

    if active-tab == "Auth" : VerticalBox {
        Text { text: "Autenticação em breve"; color: #888; }
    }
}
